---
sudo: false

language: php
matrix:
    include:
        - php: 7.2
        - php: 7.1
        - php: 7.0

install:
    - composer install

script:
    - vendor/bin/phpstan analyse
    - vendor/bin/atoum
