---
sudo: false

language: php
matrix:
    include:
        - php: 7.4
        - php: 7.3
        - php: 7.2
        - php: 7.1

install:
    - composer install

script:
    - vendor/bin/phpstan analyse
    - vendor/bin/atoum
